// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.22.0
// source: cache/v1/cache.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStringRequest) Reset() {
	*x = SetStringRequest{}
	mi := &file_cache_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStringRequest) ProtoMessage() {}

func (x *SetStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStringRequest.ProtoReflect.Descriptor instead.
func (*SetStringRequest) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *SetStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetStringRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetStringRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetStringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStringResponse) Reset() {
	*x = SetStringResponse{}
	mi := &file_cache_v1_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStringResponse) ProtoMessage() {}

func (x *SetStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStringResponse.ProtoReflect.Descriptor instead.
func (*SetStringResponse) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{1}
}

type GetStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStringRequest) Reset() {
	*x = GetStringRequest{}
	mi := &file_cache_v1_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStringRequest) ProtoMessage() {}

func (x *GetStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStringRequest.ProtoReflect.Descriptor instead.
func (*GetStringRequest) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GetStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetStringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStringResponse) Reset() {
	*x = GetStringResponse{}
	mi := &file_cache_v1_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStringResponse) ProtoMessage() {}

func (x *GetStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStringResponse.ProtoReflect.Descriptor instead.
func (*GetStringResponse) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{3}
}

func (x *GetStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DelStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelStringRequest) Reset() {
	*x = DelStringRequest{}
	mi := &file_cache_v1_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelStringRequest) ProtoMessage() {}

func (x *DelStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelStringRequest.ProtoReflect.Descriptor instead.
func (*DelStringRequest) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DelStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelStringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelStringResponse) Reset() {
	*x = DelStringResponse{}
	mi := &file_cache_v1_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelStringResponse) ProtoMessage() {}

func (x *DelStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelStringResponse.ProtoReflect.Descriptor instead.
func (*DelStringResponse) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{5}
}

var File_cache_v1_cache_proto protoreflect.FileDescriptor

const file_cache_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x14cache/v1/cache.proto\x12\bcache.v1\x1a\x1cgoogle/api/annotations.proto\"[\n" +
	"\x10SetStringRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"\x13\n" +
	"\x11SetStringResponse\"$\n" +
	"\x10GetStringRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x11GetStringResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"$\n" +
	"\x10DelStringRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x13\n" +
	"\x11DelStringResponse2\xc3\x02\n" +
	"\fCacheService\x12g\n" +
	"\tSetString\x12\x1a.cache.v1.SetStringRequest\x1a\x1b.cache.v1.SetStringResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/cache/string/{key}\x12d\n" +
	"\tGetString\x12\x1a.cache.v1.GetStringRequest\x1a\x1b.cache.v1.GetStringResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/cache/string/{key}\x12d\n" +
	"\tDelString\x12\x1a.cache.v1.DelStringRequest\x1a\x1b.cache.v1.DelStringResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/v1/cache/string/{key}B!Z\x1fgocache-service/api/cache/v1;v1b\x06proto3"

var (
	file_cache_v1_cache_proto_rawDescOnce sync.Once
	file_cache_v1_cache_proto_rawDescData []byte
)

func file_cache_v1_cache_proto_rawDescGZIP() []byte {
	file_cache_v1_cache_proto_rawDescOnce.Do(func() {
		file_cache_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_v1_cache_proto_rawDesc), len(file_cache_v1_cache_proto_rawDesc)))
	})
	return file_cache_v1_cache_proto_rawDescData
}

var file_cache_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cache_v1_cache_proto_goTypes = []any{
	(*SetStringRequest)(nil),  // 0: cache.v1.SetStringRequest
	(*SetStringResponse)(nil), // 1: cache.v1.SetStringResponse
	(*GetStringRequest)(nil),  // 2: cache.v1.GetStringRequest
	(*GetStringResponse)(nil), // 3: cache.v1.GetStringResponse
	(*DelStringRequest)(nil),  // 4: cache.v1.DelStringRequest
	(*DelStringResponse)(nil), // 5: cache.v1.DelStringResponse
}
var file_cache_v1_cache_proto_depIdxs = []int32{
	0, // 0: cache.v1.CacheService.SetString:input_type -> cache.v1.SetStringRequest
	2, // 1: cache.v1.CacheService.GetString:input_type -> cache.v1.GetStringRequest
	4, // 2: cache.v1.CacheService.DelString:input_type -> cache.v1.DelStringRequest
	1, // 3: cache.v1.CacheService.SetString:output_type -> cache.v1.SetStringResponse
	3, // 4: cache.v1.CacheService.GetString:output_type -> cache.v1.GetStringResponse
	5, // 5: cache.v1.CacheService.DelString:output_type -> cache.v1.DelStringResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_v1_cache_proto_init() }
func file_cache_v1_cache_proto_init() {
	if File_cache_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_v1_cache_proto_rawDesc), len(file_cache_v1_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_v1_cache_proto_goTypes,
		DependencyIndexes: file_cache_v1_cache_proto_depIdxs,
		MessageInfos:      file_cache_v1_cache_proto_msgTypes,
	}.Build()
	File_cache_v1_cache_proto = out.File
	file_cache_v1_cache_proto_goTypes = nil
	file_cache_v1_cache_proto_depIdxs = nil
}
